package serverfs

import (
	"encoding/base64"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"
)

const (
	configurationsDir = "configurations"
	generatedCfgFile  = "server.cfg"
)

// gameBuildPattern accepts fxserver build identifiers (numeric, or tokens like
// "latest"/"2944_0"). A stricter allow-list prevents newline/quote injection
// into the generated server.cfg.
var gameBuildPattern = regexp.MustCompile(`^[A-Za-z0-9_.-]+$`)

// resourceNamePattern accepts FiveM resource names including category-style
// paths (e.g. "[qbx]/qbx_core"). Whitespace, quotes, newlines, and shell
// metacharacters are rejected.
var resourceNamePattern = regexp.MustCompile(`^[A-Za-z0-9_./\[\]-]+$`)

// FieldDecryptor decrypts panel-encrypted field values. A nil decryptor is
// accepted when no encrypted fields are present.
type FieldDecryptor interface {
	Decrypt(ciphertext []byte) ([]byte, error)
}

// FieldCipher bundles both directions of field-level encryption and is
// required when the registry writes new encrypted values (e.g. initial
// license key on server creation), not only reads existing ones.
type FieldCipher interface {
	FieldDecryptor
	Encrypt(plaintext []byte) ([]byte, error)
}

// renderServerCfg produces a deterministic fxserver server.cfg from a
// ServerConfig and its already-decrypted license key. OneSync is deliberately
// omitted — setting it via server.cfg is deprecated as of 2026 and the
// launcher forwards it as a `+set onesync` CLI arg instead.
//
// The second return value lists sanitizer rejections (invalid values that
// were dropped from the output). Callers forward these to the panel console
// so users see why a TOML entry didn't land in their server.cfg.
func renderServerCfg(cfg *ServerConfig, licenseKey string) (string, []string) {
	var b strings.Builder
	var warnings []string

	b.WriteString("# generated by the runfive panel — DO NOT EDIT\n")
	b.WriteString("# source of truth: ../server.toml\n\n")

	fmt.Fprintf(&b, "sv_hostname %q\n", sanitizeQuoted(cfg.Name))
	fmt.Fprintf(&b, "sv_maxclients %d\n", effectiveMaxClients(cfg))

	port := effectivePort(cfg)
	fmt.Fprintf(&b, "endpoint_add_tcp \"0.0.0.0:%d\"\n", port)
	fmt.Fprintf(&b, "endpoint_add_udp \"0.0.0.0:%d\"\n", port)

	if build := strings.TrimSpace(cfg.Network.EnforceGameBuild); build != "" {
		if gameBuildPattern.MatchString(build) {
			fmt.Fprintf(&b, "sv_enforceGameBuild %s\n", build)
		} else {
			warnings = append(warnings, fmt.Sprintf("rejected enforce_game_build %q (invalid characters)", build))
		}
	}

	if licenseKey != "" {
		fmt.Fprintf(&b, "sv_licenseKey %q\n", sanitizeQuoted(licenseKey))
	}

	if len(cfg.Resources.Ensure) > 0 {
		b.WriteString("\n")
		for _, raw := range cfg.Resources.Ensure {
			res := strings.TrimSpace(raw)
			if res == "" {
				continue
			}
			if !resourceNamePattern.MatchString(res) {
				warnings = append(warnings, fmt.Sprintf("rejected resource name %q (invalid characters)", raw))
				continue
			}
			fmt.Fprintf(&b, "ensure %s\n", res)
		}
	}

	return b.String(), warnings
}

// sanitizeQuoted strips control characters that would break out of a %q-quoted
// string in fxserver's cfg parser. %q already escapes `"` and `\`, but we
// belt-and-suspender newlines to keep the generated file line-oriented.
func sanitizeQuoted(s string) string {
	return strings.Map(func(r rune) rune {
		if r == '\n' || r == '\r' || r == 0 {
			return -1
		}
		return r
	}, s)
}

func effectivePort(cfg *ServerConfig) int {
	if cfg.Network.Port > 0 {
		return cfg.Network.Port
	}
	return 30120
}

func effectiveMaxClients(cfg *ServerConfig) int {
	if cfg.Network.MaxClients > 0 {
		return cfg.Network.MaxClients
	}
	return 32
}

// writeGeneratedServerCfg renders and atomically writes the generated
// server.cfg under the server's configurations/ subdirectory. The subdir is
// intentionally NOT watched by fsnotify (addSubdirWatches only walks one
// level deep from rootDir), so writes here never trigger a reload loop.
//
// The returned warnings slice contains sanitizer rejections that the caller
// should surface to operators (panel console, logs).
func writeGeneratedServerCfg(serverDir string, cfg *ServerConfig, dec FieldDecryptor) ([]string, error) {
	licenseKey, err := decryptLicense(cfg.License.KeyEncrypted, dec)
	if err != nil {
		return nil, err
	}

	rendered, warnings := renderServerCfg(cfg, licenseKey)

	dir := filepath.Join(serverDir, configurationsDir)
	if err := os.MkdirAll(dir, 0o750); err != nil {
		return warnings, fmt.Errorf("create configurations dir: %w", err)
	}

	path := filepath.Join(dir, generatedCfgFile)
	tmp := path + ".tmp"
	if err := os.WriteFile(tmp, []byte(rendered), 0o600); err != nil {
		return warnings, fmt.Errorf("write server.cfg: %w", err)
	}
	if err := os.Rename(tmp, path); err != nil {
		return warnings, fmt.Errorf("finalize server.cfg: %w", err)
	}
	return warnings, nil
}

func decryptLicense(encoded string, dec FieldDecryptor) (string, error) {
	if encoded == "" || dec == nil {
		return "", nil
	}
	raw, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return "", fmt.Errorf("decode license ciphertext: %w", err)
	}
	plain, err := dec.Decrypt(raw)
	if err != nil {
		return "", fmt.Errorf("decrypt license: %w", err)
	}
	return string(plain), nil
}
