package serverfs

import (
	"encoding/base64"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

const (
	configurationsDir = "configurations"
	generatedCfgFile  = "server.cfg"
)

// FieldDecryptor decrypts panel-encrypted field values. A nil decryptor is
// accepted when no encrypted fields are present.
type FieldDecryptor interface {
	Decrypt(ciphertext []byte) ([]byte, error)
}

// renderServerCfg produces a deterministic fxserver server.cfg from a
// ServerConfig and its already-decrypted license key. OneSync is deliberately
// omitted — setting it via server.cfg is deprecated as of 2026 and the
// launcher forwards it as a `+set onesync` CLI arg instead.
func renderServerCfg(cfg ServerConfig, licenseKey string) string {
	var b strings.Builder

	b.WriteString("# generated by the runfive panel — DO NOT EDIT\n")
	b.WriteString("# source of truth: ../server.toml\n\n")

	fmt.Fprintf(&b, "sv_hostname %q\n", cfg.Name)
	fmt.Fprintf(&b, "sv_maxclients %d\n", effectiveMaxClients(cfg))

	port := effectivePort(cfg)
	fmt.Fprintf(&b, "endpoint_add_tcp \"0.0.0.0:%d\"\n", port)
	fmt.Fprintf(&b, "endpoint_add_udp \"0.0.0.0:%d\"\n", port)

	if cfg.Network.EnforceGameBuild != "" {
		fmt.Fprintf(&b, "sv_enforceGameBuild %s\n", cfg.Network.EnforceGameBuild)
	}

	if licenseKey != "" {
		fmt.Fprintf(&b, "sv_licenseKey %q\n", licenseKey)
	}

	if len(cfg.Resources.Ensure) > 0 {
		b.WriteString("\n")
		for _, res := range cfg.Resources.Ensure {
			fmt.Fprintf(&b, "ensure %s\n", res)
		}
	}

	return b.String()
}

func effectivePort(cfg ServerConfig) int {
	if cfg.Network.Port > 0 {
		return cfg.Network.Port
	}
	return 30120
}

func effectiveMaxClients(cfg ServerConfig) int {
	if cfg.Network.MaxClients > 0 {
		return cfg.Network.MaxClients
	}
	return 32
}

// writeGeneratedServerCfg renders and atomically writes the generated
// server.cfg under the server's configurations/ subdirectory. The subdir is
// intentionally NOT watched by fsnotify (addSubdirWatches only walks one
// level deep from rootDir), so writes here never trigger a reload loop.
func writeGeneratedServerCfg(serverDir string, cfg ServerConfig, dec FieldDecryptor) error {
	licenseKey, err := decryptLicense(cfg.License.KeyEncrypted, dec)
	if err != nil {
		return err
	}

	rendered := renderServerCfg(cfg, licenseKey)

	dir := filepath.Join(serverDir, configurationsDir)
	if err := os.MkdirAll(dir, 0o750); err != nil {
		return fmt.Errorf("create configurations dir: %w", err)
	}

	path := filepath.Join(dir, generatedCfgFile)
	tmp := path + ".tmp"
	if err := os.WriteFile(tmp, []byte(rendered), 0o600); err != nil {
		return fmt.Errorf("write server.cfg: %w", err)
	}
	if err := os.Rename(tmp, path); err != nil {
		return fmt.Errorf("finalize server.cfg: %w", err)
	}
	return nil
}

func decryptLicense(encoded string, dec FieldDecryptor) (string, error) {
	if encoded == "" || dec == nil {
		return "", nil
	}
	raw, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return "", fmt.Errorf("decode license ciphertext: %w", err)
	}
	plain, err := dec.Decrypt(raw)
	if err != nil {
		return "", fmt.Errorf("decrypt license: %w", err)
	}
	return string(plain), nil
}
